# mongodb-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: rocket-chat
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
      containers:
      - name: mongodb
        image: bitnami/mongodb:5.0
        env:
        - name: MONGODB_REPLICA_SET_MODE
          value: "primary"
        - name: MONGODB_REPLICA_SET_NAME
          value: "rs0"
        - name: MONGODB_PORT_NUMBER
          value: "27017"
        - name: MONGODB_INITIAL_PRIMARY_HOST
          value: "mongodb"
        - name: MONGODB_INITIAL_PRIMARY_PORT_NUMBER
          value: "27017"
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: "mongodb"
        - name: MONGODB_ENABLE_JOURNAL
          value: "true"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /bitnami/mongodb
      volumes:
      - name: mongodb-data
        emptyDir: {}
